spring:
  datasource:
    url:
    username:
    password:

  jpa:
    properties:
      hibernate:
        dialect:
        ddl_auto: update


logging:
  level:
    org:
      springframework:
        security: DEBUG